export function buildBuildWizardWorkspaceComposedOptions(options: any) {
  return {
    LIGHTBOX_ZOOM_MAX: options.LIGHTBOX_ZOOM_MAX, LIGHTBOX_ZOOM_MIN: options.LIGHTBOX_ZOOM_MIN,
    LIGHTBOX_ZOOM_STEP: options.LIGHTBOX_ZOOM_STEP, TAB_DEFAULT_PHASE_KEY: options.TAB_DEFAULT_PHASE_KEY,
    activeTab: options.activeTab, addStep: options.addStep, aiBusy: options.aiBusy, aiPayloadJson: options.aiPayloadJson,
    aiPromptText: options.aiPromptText, aiToolsOpen: options.aiToolsOpen,
    attachExistingDocByReceiptId: options.attachExistingDocByReceiptId,
    attachExistingDocByStepId: options.attachExistingDocByStepId,
    attachExistingDocFilterByReceiptId: options.attachExistingDocFilterByReceiptId,
    attachExistingDocFilterByStepId: options.attachExistingDocFilterByStepId,
    attachExistingPickerOpenByStepId: options.attachExistingPickerOpenByStepId,
    attachableProjectDocuments: options.attachableProjectDocuments,
    authorityContacts: options.authorityContacts,
    buildEntryPoint: options.buildEntryPoint,
    closeLightbox: options.closeLightbox,
    completedSteps: options.completedSteps,
    contactTypeChipClass: options.contactTypeChipClass,
    contactTypeLabel: options.contactTypeLabel,
    contacts: options.contacts,
    deleteContactAssignment: options.deleteContactAssignment,
    deleteStep: options.deleteStep,
    deletingDocumentId: options.deletingDocumentId,
    deletingNoteId: options.deletingNoteId,
    dependencyCandidateByStepId: options.dependencyCandidateByStepId,
    deskAssignmentPhaseKey: options.deskAssignmentPhaseKey,
    deskAssignmentStepId: options.deskAssignmentStepId,
    deskAutoAssignBusy: options.deskAutoAssignBusy,
    deskContactAssignmentCountById: options.deskContactAssignmentCountById,
    deskContactDraft: options.deskContactDraft,
    deskContactQuery: options.deskContactQuery,
    deskContactTypeFilter: options.deskContactTypeFilter,
    deskContacts: options.deskContacts,
    deskSelectedContactId: options.deskSelectedContactId,
    docKind: options.docKind,
    docKindOptions: options.docKindOptions,
    docPhaseKey: options.docPhaseKey,
    docStepId: options.docStepId,
    documentManagerKindFilter: options.documentManagerKindFilter, documentManagerPhaseFilter: options.documentManagerPhaseFilter,
    documentManagerQuery: options.documentManagerQuery, documentManagerSearchLoading: options.documentManagerSearchLoading,
    documentManagerStepFilter: options.documentManagerStepFilter,
    documentSavingId: options.documentSavingId,
    documents: options.documents,
    dragOverInsertIndex: options.dragOverInsertIndex,
    dragOverParentStepId: options.dragOverParentStepId,
    draggingStepId: options.draggingStepId,
    editingNoteTextById: options.editingNoteTextById,
    editingReceiptDocumentIdByStep: options.editingReceiptDocumentIdByStep,
    expandedStepById: options.expandedStepById,
    fetchSingletreeRecoveryStatus: options.fetchSingletreeRecoveryStatus,
    filteredDeskContacts: options.filteredDeskContacts,
    filteredTabSteps: options.filteredTabSteps,
    footerRange: options.footerRange,
    formatCurrency: options.formatCurrency,
    formatDate: options.formatDate,
    formatTimelineDate: options.formatTimelineDate,
    focusStepInBuildView: options.focusStepInBuildView,
    generateStepsFromAi: options.generateStepsFromAi,
    getTaskEffectiveDate: options.getTaskEffectiveDate,
    inlineEditingReceiptFieldByDocId: options.inlineEditingReceiptFieldByDocId,
    inlineReceiptDraftByDocId: options.inlineReceiptDraftByDocId,
    isPlanPreviewDoc: options.isPlanPreviewDoc,
    isSpreadsheetPreviewDoc: options.isSpreadsheetPreviewDoc,
    isTemplateProject: options.isTemplateProject,
    lightboxDoc: options.lightboxDoc,
    lightboxSpreadsheetSheetIndex: options.lightboxSpreadsheetSheetIndex,
    lightboxSupportsZoom: options.lightboxSupportsZoom,
    lightboxZoom: options.lightboxZoom,
    lotSizeDetectedUnit: options.lotSizeDetectedUnit,
    lotSizeInput: options.lotSizeInput,
    lotSizeInputToSqftAuto: options.lotSizeInputToSqftAuto,
    moveStepModalStep: options.moveStepModalStep,
    moveStepModalTargetTab: options.moveStepModalTargetTab,
    moveTaskModalTargetStepId: options.moveTaskModalTargetStepId,
    movingStep: options.movingStep,
    normalizeContactType: options.normalizeContactType,
    noteDraftByStep: options.noteDraftByStep,
    noteEditorOpenByStep: options.noteEditorOpenByStep,
    onOpenDocumentPreview: options.onOpenDocumentPreview,
    onToast: options.onToast,
    openDocumentPreview: options.openDocumentPreview,
    packageForAi: options.packageForAi,
    parseTaskMetaFromReceiptNotes: options.parseTaskMetaFromReceiptNotes,
    permitStatusOptions: options.permitStatusOptions,
    phaseTaskListCardRef: options.phaseTaskListCardRef,
    project: options.project,
    projectDeskOpen: options.projectDeskOpen,
    projectDeskSteps: options.projectDeskSteps,
    projectDraft: options.projectDraft,
    projectId: options.projectId,
    projectOverviewOpen: options.projectOverviewOpen,
    projectPhotosSection: options.projectPhotosSection,
    purchaseUnitOptions: options.purchaseUnitOptions,
    receiptDraftByStep: options.receiptDraftByStep,
    receiptEditorOpenByStep: options.receiptEditorOpenByStep,
    receiptEditorRefByStepId: options.receiptEditorRefByStepId,
    receiptRowRefByDocId: options.receiptRowRefByDocId,
    recoveryJobId: options.recoveryJobId,
    recoveryPolling: options.recoveryPolling,
    recoveryReportJson: options.recoveryReportJson,
    recoveryReportOpen: options.recoveryReportOpen,
    recoveryStagedCount: options.recoveryStagedCount,
    recoveryStagedRoot: options.recoveryStagedRoot,
    recoveryStatus: options.recoveryStatus,
    refreshingActualCostByStepId: options.refreshingActualCostByStepId,
    renderDocumentGallery: options.renderDocumentGallery,
    replaceFileInputByDocId: options.replaceFileInputByDocId,
    replacingDocumentId: options.replacingDocumentId,
    savePhaseDateRange: options.savePhaseDateRange,
    saving: options.saving,
    savingNoteId: options.savingNoteId,
    selectableDocSteps: options.selectableDocSteps,
    selectedContactAssignments: options.selectedContactAssignments,
    selectedDeskContact: options.selectedDeskContact,
    setActiveTab: options.setActiveTab,
    setAiToolsOpen: options.setAiToolsOpen,
    setAttachExistingDocByReceiptId: options.setAttachExistingDocByReceiptId,
    setAttachExistingDocByStepId: options.setAttachExistingDocByStepId,
    setAttachExistingDocFilterByReceiptId: options.setAttachExistingDocFilterByReceiptId,
    setAttachExistingDocFilterByStepId: options.setAttachExistingDocFilterByStepId,
    setAttachExistingPickerOpenByStepId: options.setAttachExistingPickerOpenByStepId,
    setDependencyCandidateByStepId: options.setDependencyCandidateByStepId,
    setDeskAssignmentPhaseKey: options.setDeskAssignmentPhaseKey,
    setDeskAssignmentStepId: options.setDeskAssignmentStepId,
    setDeskContactDraft: options.setDeskContactDraft,
    setDeskContactQuery: options.setDeskContactQuery,
    setDeskContactTypeFilter: options.setDeskContactTypeFilter,
    setDeskCreateMode: options.setDeskCreateMode,
    setDeskSelectedContactId: options.setDeskSelectedContactId,
    setDocKind: options.setDocKind,
    setDocPhaseKey: options.setDocPhaseKey,
    setDocStepId: options.setDocStepId,
    setDocumentManagerKindFilter: options.setDocumentManagerKindFilter,
    setDocumentManagerPhaseFilter: options.setDocumentManagerPhaseFilter,
    setDocumentManagerQuery: options.setDocumentManagerQuery,
    setDocumentManagerStepFilter: options.setDocumentManagerStepFilter,
    setDocumentUploadBusy: options.setDocumentUploadBusy,
    setDocumentUploadFile: options.setDocumentUploadFile,
    setDocumentUploadModalOpen: options.setDocumentUploadModalOpen,
    setDragOverInsertIndex: options.setDragOverInsertIndex,
    setDragOverParentStepId: options.setDragOverParentStepId,
    setEditingNoteTextById: options.setEditingNoteTextById,
    setEditingReceiptDocumentIdByStep: options.setEditingReceiptDocumentIdByStep,
    setExpandedStepById: options.setExpandedStepById,
    setInlineReceiptDraftByDocId: options.setInlineReceiptDraftByDocId,
    setLightboxSpreadsheetSheetIndex: options.setLightboxSpreadsheetSheetIndex,
    setLotSizeInput: options.setLotSizeInput,
    setMoveStepModalStepId: options.setMoveStepModalStepId,
    setMoveStepModalTargetTab: options.setMoveStepModalTargetTab,
    setMoveTaskModalDocId: options.setMoveTaskModalDocId,
    setMoveTaskModalTargetStepId: options.setMoveTaskModalTargetStepId,
    setNoteDraftByStep: options.setNoteDraftByStep,
    setNoteEditorOpenByStep: options.setNoteEditorOpenByStep,
    setProjectDeskOpen: options.setProjectDeskOpen,
    setProjectDraft: options.setProjectDraft,
    setProjectOverviewOpen: options.setProjectOverviewOpen,
    setReceiptAttachmentDraftByStep: options.setReceiptAttachmentDraftByStep,
    setReceiptDraftByStep: options.setReceiptDraftByStep,
    setReceiptEditorOpenByStep: options.setReceiptEditorOpenByStep,
    setRecoveryJobId: options.setRecoveryJobId,
    setRecoveryPolling: options.setRecoveryPolling,
    setRecoveryReportJson: options.setRecoveryReportJson,
    setRecoveryReportOpen: options.setRecoveryReportOpen,
    setRecoveryStatus: options.setRecoveryStatus,
    setStepCardAssigneeIdFilter: options.setStepCardAssigneeIdFilter,
    setStepCardAssigneeTypeFilter: options.setStepCardAssigneeTypeFilter,
    setStepCardTextFilter: options.setStepCardTextFilter,
    setStepContactCandidateByStepId: options.setStepContactCandidateByStepId,
    setStepContactPickerOpenByStepId: options.setStepContactPickerOpenByStepId,
    setStepInfoModalStepId: options.setStepInfoModalStepId,
    setTaskAttachmentsModalDocId: options.setTaskAttachmentsModalDocId,
    setTopbarSearchOpen: options.setTopbarSearchOpen,
    setTopbarSearchQuery: options.setTopbarSearchQuery,
    stepById: options.stepById,
    stepByIdMap: options.stepByIdMap,
    stepCardAssigneeIdFilter: options.stepCardAssigneeIdFilter,
    stepCardAssigneeTypeFilter: options.stepCardAssigneeTypeFilter,
    stepCardTextFilter: options.stepCardTextFilter,
    stepDrafts: options.stepDrafts,
    stepEditModalDependencyIds: options.stepEditModalDependencyIds,
    stepEditModalDependencyOptions: options.stepEditModalDependencyOptions,
    stepEditModalDraft: options.stepEditModalDraft,
    stepEditModalStep: options.stepEditModalStep,
    stepEditSaving: options.stepEditSaving,
    stepInfoModalStep: options.stepInfoModalStep,
    stepPhaseBucket: options.stepPhaseBucket,
    stickyHeadHeight: options.stickyHeadHeight,
    stickyHeadRef: options.stickyHeadRef,
    stickyTopOffset: options.stickyTopOffset,
    steps: options.steps,
    taskTypeOptions: options.taskTypeOptions,
    taskUsesManualDateOverride: options.taskUsesManualDateOverride,
    toNumberOrNull: options.toNumberOrNull,
    toStringOrNull: options.toStringOrNull,
    toggleStep: options.toggleStep,
    topbarSearchBoxRef: options.topbarSearchBoxRef,
    topbarSearchLoading: options.topbarSearchLoading,
    topbarSearchOpen: options.topbarSearchOpen,
    topbarSearchQuery: options.topbarSearchQuery,
    updateProject: options.updateProject,
    uploadDocument: options.uploadDocument,
    verifiedActualCostSignatureByStepId: options.verifiedActualCostSignatureByStepId,
    ...options.activeTabTree,
    ...options.confirmationActions,
    ...options.deskActions,
    ...options.documentActions,
    ...options.documentManagerData,
    ...options.launcherActions,
    ...options.noteDocumentActions,
    ...options.overviewData,
    ...options.phaseRangeActions,
    ...options.stepUiActions,
    ...options.stepWorkspaceMeta,
    ...options.workflowActions,
    ...options.workspaceSelectionData,
    ...options.workspaceUiCallbacks,
  };
}
