import { useBuildWizardDocumentActionSetup } from './useBuildWizardDocumentActionSetup';
import { useBuildWizardPhaseRangeAutoSync } from './useBuildWizardPhaseRangeAutoSync';
import { useBuildWizardWorkflowActionSetup } from './useBuildWizardWorkflowActionSetup';

export function useBuildWizardPageDocumentWorkflowActions(options: any) {
  const documentActions = useBuildWizardDocumentActionSetup({
    attachExistingDocByReceiptId: options.state.attachExistingDocByReceiptId,
    attachExistingDocByStepId: options.state.attachExistingDocByStepId,
    buildDocumentDraftDeps: {
      documentDrafts: options.state.documentDrafts,
      parseTaskMetaFromReceiptNotes: options.parseTaskMetaFromReceiptNotes,
      setTaskDateOverrideInReceiptNotes: options.setTaskDateOverrideInReceiptNotes,
      taskUsesManualDateOverride: options.taskUsesManualDateOverride,
    },
    contacts: options.buildWizard.contacts,
    createStepReceipt: options.buildWizard.createStepReceipt,
    documents: options.buildWizard.documents,
    documentSavingId: options.state.documentSavingId,
    editingReceiptDocumentIdByStep: options.state.editingReceiptDocumentIdByStep,
    inlineReceiptDraftByDocId: options.state.inlineReceiptDraftByDocId,
    moveTaskModalDoc: options.workspace.documentManagerData.moveTaskModalDoc,
    moveTaskModalTargetStepId: options.state.moveTaskModalTargetStepId,
    onToast: options.onToast,
    parseTaskMetaFromReceiptNotes: options.parseTaskMetaFromReceiptNotes,
    pendingScrollReceiptId: options.state.pendingScrollReceiptId,
    projectId: options.buildWizard.projectId,
    receiptAttachmentDraftByStep: options.state.receiptAttachmentDraftByStep,
    receiptDraftByStep: options.state.receiptDraftByStep,
    receiptEditorRefByStepId: options.state.receiptEditorRefByStepId,
    receiptRowRefByDocId: options.state.receiptRowRefByDocId,
    resolvePhaseDateRange: options.workspace.phaseRangeActions.resolvePhaseDateRange,
    savePhaseDateRange: options.buildWizard.savePhaseDateRange,
    setAttachExistingDocByReceiptId: options.state.setAttachExistingDocByReceiptId,
    setAttachExistingDocByStepId: options.state.setAttachExistingDocByStepId,
    setAttachExistingDocFilterByReceiptId: options.state.setAttachExistingDocFilterByReceiptId,
    setDocumentDrafts: options.state.setDocumentDrafts,
    setDocumentSavingId: options.state.setDocumentSavingId,
    setEditingReceiptDocumentIdByStep: options.state.setEditingReceiptDocumentIdByStep,
    setInlineEditingReceiptFieldByDocId: options.state.setInlineEditingReceiptFieldByDocId,
    setInlineReceiptDraftByDocId: options.state.setInlineReceiptDraftByDocId,
    setMoveTaskModalDocId: options.state.setMoveTaskModalDocId,
    setMoveTaskModalTargetStepId: options.state.setMoveTaskModalTargetStepId,
    setPendingScrollReceiptId: options.state.setPendingScrollReceiptId,
    setReceiptAttachmentDraftByStep: options.state.setReceiptAttachmentDraftByStep,
    setReceiptDraftByStep: options.state.setReceiptDraftByStep,
    setReceiptEditorOpenByStep: options.state.setReceiptEditorOpenByStep,
    setTaskAttachmentsModalDocId: options.state.setTaskAttachmentsModalDocId,
    stepByIdMap: options.workspace.workspaceData.stepByIdMap,
    stepPhaseBucket: options.stepPhaseBucket,
    taskUsesManualDateOverride: options.taskUsesManualDateOverride,
    updateDocument: options.buildWizard.updateDocument,
    uploadDocument: options.buildWizard.uploadDocument,
  });
  const workflowActions = useBuildWizardWorkflowActionSetup({
    activeTabTreeRows: options.workspace.activeTabTree.activeTabTreeRows,
    clampStepDatesWithinRange: documentActions.clampStepDatesWithinRange,
    clearedLegacyTaskDatesByProjectRef: options.state.clearedLegacyTaskDatesByProjectRef,
    clearStepDraft: options.stepUiActions.clearStepDraft,
    documents: options.buildWizard.documents,
    draggingStepId: options.state.draggingStepId,
    expandPhaseRangeForStep: documentActions.expandPhaseRangeForStep,
    fetchSingletreeRecoveryStatus: options.buildWizard.fetchSingletreeRecoveryStatus,
    generateStepsFromAi: options.buildWizard.generateStepsFromAi,
    isAdmin: options.isAdmin,
    isLegacyAutoStampedTaskDate: options.isLegacyAutoStampedTaskDate,
    onToast: options.onToast,
    openProject: options.buildWizard.openProject,
    parseTaskMetaFromReceiptNotes: options.parseTaskMetaFromReceiptNotes,
    projectId: options.buildWizard.projectId,
    recoverSingletreeDocuments: options.buildWizard.recoverSingletreeDocuments,
    recoveryBusy: options.buildWizard.recoveryBusy,
    recoveryJobId: options.state.recoveryJobId,
    recoveryPolling: options.state.recoveryPolling,
    recoveryStagedRoot: options.state.recoveryStagedRoot,
    recoveryStatus: options.state.recoveryStatus,
    recoveryUploadBusy: options.state.recoveryUploadBusy,
    recoveryUploadInputRef: options.state.recoveryUploadInputRef,
    reorderSteps: options.buildWizard.reorderSteps,
    requestConfirmation: options.workspace.confirmationActions.requestConfirmation,
    setDragOverInsertIndex: options.state.setDragOverInsertIndex,
    setDragOverParentStepId: options.state.setDragOverParentStepId,
    setDraggingStepId: options.state.setDraggingStepId,
    setRecoveryJobId: options.state.setRecoveryJobId,
    setRecoveryPolling: options.state.setRecoveryPolling,
    setRecoveryReportJson: options.state.setRecoveryReportJson,
    setRecoveryReportOpen: options.state.setRecoveryReportOpen,
    setRecoveryStagedCount: options.state.setRecoveryStagedCount,
    setRecoveryStagedRoot: options.state.setRecoveryStagedRoot,
    setRecoveryStatus: options.state.setRecoveryStatus,
    setRecoveryUploadBusy: options.state.setRecoveryUploadBusy,
    setRecoveryUploadToken: options.state.setRecoveryUploadToken,
    setStepEditModalStepId: options.state.setStepEditModalStepId,
    setStepEditSaving: options.state.setStepEditSaving,
    setTaskDateOverrideInReceiptNotes: options.setTaskDateOverrideInReceiptNotes,
    stageSingletreeSourceFiles: options.buildWizard.stageSingletreeSourceFiles,
    stepById: options.workspace.workspaceData.stepById,
    stepDrafts: options.state.stepDrafts,
    stepEditModalStep: options.workspace.workspaceData.stepEditModalStep,
    stepEditSaving: options.state.stepEditSaving,
    steps: options.buildWizard.steps,
    updateStep: options.buildWizard.updateStep,
  });
  useBuildWizardPhaseRangeAutoSync({
    projectId: options.buildWizard.projectId,
    resolvePhaseDateRange: options.workspace.phaseRangeActions.resolvePhaseDateRange,
    savePhaseDateRange: options.buildWizard.savePhaseDateRange,
    stepPhaseBucket: options.stepPhaseBucket,
    steps: options.buildWizard.steps,
    toStringOrNull: options.toStringOrNull,
  });

  return { documentActions, workflowActions };
}
