import { useBuildWizardProjectDeskEffects } from './useBuildWizardProjectDeskEffects';
import { useBuildWizardSelectionEffects } from './useBuildWizardSelectionEffects';
import { useBuildWizardWorkspaceChromeEffects } from './useBuildWizardWorkspaceChromeEffects';
import { useBuildWizardWorkspaceCleanupEffects } from './useBuildWizardWorkspaceCleanupEffects';
import { useBuildWizardWorkspaceSearchEffects } from './useBuildWizardWorkspaceSearchEffects';

export function useBuildWizardPageEffects(options: any) {
  useBuildWizardWorkspaceChromeEffects({
    activeTab: options.state.activeTab,
    initialUrlState: options.state.initialUrlState,
    lotSizeSqftToDisplayInput: options.lotSizeSqftToDisplayInput,
    onToast: options.onToast,
    openProject: options.buildWizard.openProject,
    phaseTaskListCardRef: options.state.phaseTaskListCardRef,
    previousActiveTabRef: options.state.previousActiveTabRef,
    projectId: options.buildWizard.projectId,
    questionnaire: options.buildWizard.questionnaire,
    setActiveTab: options.state.setActiveTab,
    setBuildEntryPoint: options.state.setBuildEntryPoint,
    setDropdownSettings: options.state.setDropdownSettings,
    setLotSizeInput: options.state.setLotSizeInput,
    setProjectDraft: options.state.setProjectDraft,
    setRefreshingActualCostByStepId: options.state.setRefreshingActualCostByStepId,
    setStickyHeadHeight: options.state.setStickyHeadHeight,
    setStickyTopOffset: options.state.setStickyTopOffset,
    setVerifiedActualCostSignatureByStepId: options.state.setVerifiedActualCostSignatureByStepId,
    setView: options.state.setView,
    stickyHeadHeight: options.state.stickyHeadHeight,
    stickyHeadRef: options.state.stickyHeadRef,
    stickyTopOffset: options.state.stickyTopOffset,
    view: options.state.view,
  });
  useBuildWizardWorkspaceCleanupEffects({
    documents: options.buildWizard.documents,
    moveTaskModalDocId: options.state.moveTaskModalDocId,
    setAttachExistingDocFilterByReceiptId: options.state.setAttachExistingDocFilterByReceiptId,
    setAttachExistingDocFilterByStepId: options.state.setAttachExistingDocFilterByStepId,
    setAttachExistingPickerOpenByStepId: options.state.setAttachExistingPickerOpenByStepId,
    setDependencyCandidateByStepId: options.state.setDependencyCandidateByStepId,
    setExpandedStepById: options.state.setExpandedStepById,
    setMoveTaskModalDocId: options.state.setMoveTaskModalDocId,
    setMoveTaskModalTargetStepId: options.state.setMoveTaskModalTargetStepId,
    setReceiptAttachmentDraftByStep: options.state.setReceiptAttachmentDraftByStep,
    setReceiptDraftByStep: options.state.setReceiptDraftByStep,
    setReceiptEditorOpenByStep: options.state.setReceiptEditorOpenByStep,
    setStepDrafts: options.state.setStepDrafts,
    setStepInfoModalStepId: options.state.setStepInfoModalStepId,
    setTaskAttachmentsModalDocId: options.state.setTaskAttachmentsModalDocId,
    stepEditModalStepId: options.state.stepEditModalStepId,
    stepInfoModalStepId: options.state.stepInfoModalStepId,
    steps: options.buildWizard.steps,
    taskAttachmentsModalDocId: options.state.taskAttachmentsModalDocId,
  });
  useBuildWizardWorkspaceSearchEffects({
    documentManagerQuery: options.state.documentManagerQuery,
    projectId: options.buildWizard.projectId,
    searchContent: options.buildWizard.searchContent,
    setDocumentManagerSearchLoading: options.state.setDocumentManagerSearchLoading,
    setDocumentManagerSearchResults: options.state.setDocumentManagerSearchResults,
    setTopbarSearchDocumentResults: options.state.setTopbarSearchDocumentResults,
    setTopbarSearchLoading: options.state.setTopbarSearchLoading,
    setTopbarSearchOpen: options.state.setTopbarSearchOpen,
    steps: options.buildWizard.steps,
    topbarSearchBoxRef: options.state.topbarSearchBoxRef,
    topbarSearchFocusStepId: options.state.topbarSearchFocusStepId,
    topbarSearchOpen: options.state.topbarSearchOpen,
    topbarSearchQuery: options.state.topbarSearchQuery,
  });
  useBuildWizardProjectDeskEffects({
    deskContacts: options.workspaceData.deskContacts,
    deskCreateMode: options.state.deskCreateMode,
    deskSelectedContactId: options.state.deskSelectedContactId,
    documentManagerLinkedStepFilterOptions: options.documentManagerData.documentManagerLinkedStepFilterOptions,
    documentManagerStepFilter: options.state.documentManagerStepFilter,
    documents: options.buildWizard.documents,
    docStepId: options.state.docStepId,
    normalizeContactType: options.normalizeContactType,
    parseTaskMetaFromReceiptNotes: options.parseTaskMetaFromReceiptNotes,
    projectDeskOpen: options.state.projectDeskOpen,
    selectedDeskContact: options.workspaceData.selectedDeskContact,
    selectableDocSteps: options.workspaceSelectionData.selectableDocSteps,
    setDeskContactDraft: options.state.setDeskContactDraft,
    setDeskCreateMode: options.state.setDeskCreateMode,
    setDeskSelectedContactId: options.state.setDeskSelectedContactId,
    setDocStepId: options.state.setDocStepId,
    setDocumentDrafts: options.state.setDocumentDrafts,
    setDocumentManagerKindFilter: options.state.setDocumentManagerKindFilter,
    setDocumentManagerPhaseFilter: options.state.setDocumentManagerPhaseFilter,
    setDocumentManagerQuery: options.state.setDocumentManagerQuery,
    setDocumentManagerStepFilter: options.state.setDocumentManagerStepFilter,
    setDocumentUploadFile: options.state.setDocumentUploadFile,
    setDocumentUploadModalOpen: options.state.setDocumentUploadModalOpen,
    taskUsesManualDateOverride: options.taskUsesManualDateOverride,
  });
  useBuildWizardSelectionEffects({
    moveStepModalStepId: options.state.moveStepModalStepId,
    phaseProgressOrder: options.PHASE_PROGRESS_ORDER,
    setMoveStepModalStepId: options.state.setMoveStepModalStepId,
    setMoveStepModalTargetTab: options.state.setMoveStepModalTargetTab,
    setStepCardAssigneeIdFilter: options.state.setStepCardAssigneeIdFilter,
    setStepEditModalStepId: options.state.setStepEditModalStepId,
    stepById: options.workspaceData.stepById,
    stepCardAssigneeIdFilter: options.state.stepCardAssigneeIdFilter,
    stepEditModalStepId: options.state.stepEditModalStepId,
    stepFilterContactOptions: options.stepWorkspaceMeta.stepFilterContactOptions,
    stepPhaseBucket: options.stepPhaseBucket,
  });
}
