import { TAB_DEFAULT_PHASE_KEY } from '../../components/pages/build-wizard/buildWizardConstants';
import { buildBuildWizardWorkspaceComposedOptions } from './buildBuildWizardWorkspaceComposedOptions';
import { LIGHTBOX_ZOOM_MAX, LIGHTBOX_ZOOM_MIN, LIGHTBOX_ZOOM_STEP, TASK_TYPE_OPTIONS } from './buildWizardPageRenderConstants';
import { useBuildWizardWorkspaceComposedProps } from './useBuildWizardWorkspaceComposedProps';

export function useBuildWizardPageRenderSetup(options: any) {
  return useBuildWizardWorkspaceComposedProps(buildBuildWizardWorkspaceComposedOptions({
    LIGHTBOX_ZOOM_MAX, LIGHTBOX_ZOOM_MIN, LIGHTBOX_ZOOM_STEP, TAB_DEFAULT_PHASE_KEY,
    activeTab: options.state.activeTab, activeTabTree: options.workspace.activeTabTree, addStep: options.buildWizard.addStep, aiBusy: options.buildWizard.aiBusy, aiPayloadJson: options.buildWizard.aiPayloadJson, aiPromptText: options.buildWizard.aiPromptText, aiToolsOpen: options.state.aiToolsOpen,
    attachExistingDocByReceiptId: options.state.attachExistingDocByReceiptId, attachExistingDocByStepId: options.state.attachExistingDocByStepId, attachExistingDocFilterByReceiptId: options.state.attachExistingDocFilterByReceiptId, attachExistingDocFilterByStepId: options.state.attachExistingDocFilterByStepId, attachExistingPickerOpenByStepId: options.state.attachExistingPickerOpenByStepId,
    attachableProjectDocuments: options.workspace.workspaceSelectionData.attachableProjectDocuments, authorityContacts: options.workspace.workspaceData.authorityContacts, buildEntryPoint: options.state.buildEntryPoint, closeLightbox: options.workspace.documentPreview.closeLightbox, completedSteps: options.workspace.workspaceData.completedSteps, confirmationActions: options.workspace.confirmationActions, contactTypeChipClass: options.contactTypeChipClass, contactTypeLabel: options.contactTypeLabel, contacts: options.buildWizard.contacts,
    deleteContactAssignment: options.buildWizard.deleteContactAssignment, deleteStep: options.buildWizard.deleteStep, deletingDocumentId: options.state.deletingDocumentId, deletingNoteId: options.state.deletingNoteId, dependencyCandidateByStepId: options.state.dependencyCandidateByStepId, deskActions: options.actions.deskActions,
    deskAssignmentPhaseKey: options.state.deskAssignmentPhaseKey, deskAssignmentStepId: options.state.deskAssignmentStepId, deskAutoAssignBusy: options.state.deskAutoAssignBusy, deskContactAssignmentCountById: options.workspace.workspaceData.deskContactAssignmentCountById, deskContactDraft: options.state.deskContactDraft, deskContactQuery: options.state.deskContactQuery, deskContactTypeFilter: options.state.deskContactTypeFilter, deskContacts: options.workspace.workspaceData.deskContacts, deskSelectedContactId: options.state.deskSelectedContactId,
    docKind: options.state.docKind, docKindOptions: options.workspace.dropdownData.docKindOptions, docPhaseKey: options.state.docPhaseKey, docStepId: options.state.docStepId, documentActions: options.actions.documentActions, documentManagerData: options.workspace.documentManagerData, documentManagerKindFilter: options.state.documentManagerKindFilter, documentManagerPhaseFilter: options.state.documentManagerPhaseFilter,
    documentManagerQuery: options.state.documentManagerQuery, documentManagerSearchLoading: options.state.documentManagerSearchLoading, documentManagerStepFilter: options.state.documentManagerStepFilter, documentSavingId: options.state.documentSavingId, documents: options.buildWizard.documents,
    dragOverInsertIndex: options.state.dragOverInsertIndex, dragOverParentStepId: options.state.dragOverParentStepId, draggingStepId: options.state.draggingStepId, editingNoteTextById: options.state.editingNoteTextById, editingReceiptDocumentIdByStep: options.state.editingReceiptDocumentIdByStep, expandedStepById: options.state.expandedStepById,
    fetchSingletreeRecoveryStatus: options.buildWizard.fetchSingletreeRecoveryStatus, filteredDeskContacts: options.workspace.workspaceData.filteredDeskContacts, filteredTabSteps: options.workspace.workspaceData.filteredTabSteps, footerRange: options.state.footerRange, formatCurrency: options.formatCurrency, formatDate: options.formatDate, formatTimelineDate: options.formatTimelineDate,
    focusStepInBuildView: options.actions.workspaceUiCallbacks.focusStepInBuildView, generateStepsFromAi: options.buildWizard.generateStepsFromAi, getTaskEffectiveDate: options.getTaskEffectiveDate, inlineEditingReceiptFieldByDocId: options.state.inlineEditingReceiptFieldByDocId, inlineReceiptDraftByDocId: options.state.inlineReceiptDraftByDocId,
    isPlanPreviewDoc: options.workspace.documentPreview.isPlanPreviewDoc, isSpreadsheetPreviewDoc: options.workspace.documentPreview.isSpreadsheetPreviewDoc, isTemplateProject: options.actions.isTemplateProject, launcherActions: options.actions.launcherActions, lightboxDoc: options.state.lightboxDoc, lightboxSpreadsheetSheetIndex: options.state.lightboxSpreadsheetSheetIndex,
    lightboxSupportsZoom: options.actions.lightboxSupportsZoom, lightboxZoom: options.state.lightboxZoom, lotSizeDetectedUnit: options.workspace.dropdownData.lotSizeDetectedUnit, lotSizeInput: options.state.lotSizeInput, lotSizeInputToSqftAuto: options.lotSizeInputToSqftAuto, moveStepModalStep: options.workspace.workspaceData.moveStepModalStep, moveStepModalTargetTab: options.state.moveStepModalTargetTab,
    moveTaskModalTargetStepId: options.state.moveTaskModalTargetStepId, movingStep: options.state.movingStep, normalizeContactType: options.normalizeContactType, noteDocumentActions: options.actions.noteDocumentActions, noteDraftByStep: options.state.noteDraftByStep, noteEditorOpenByStep: options.state.noteEditorOpenByStep,
    onOpenDocumentPreview: options.workspace.documentPreview.openDocumentPreview, onToast: options.onToast, openDocumentPreview: options.workspace.documentPreview.openDocumentPreview, overviewData: options.workspace.overviewData, packageForAi: options.buildWizard.packageForAi, parseTaskMetaFromReceiptNotes: options.parseTaskMetaFromReceiptNotes,
    permitStatusOptions: options.workspace.dropdownData.permitStatusOptions, phaseRangeActions: options.workspace.phaseRangeActions, phaseTaskListCardRef: options.state.phaseTaskListCardRef, project: options.buildWizard.project, projectDeskOpen: options.state.projectDeskOpen, projectDeskSteps: options.workspace.workspaceData.projectDeskSteps, projectDraft: options.state.projectDraft, projectId: options.buildWizard.projectId,
    projectOverviewOpen: options.state.projectOverviewOpen, projectPhotosSection: options.actions.renderers.projectPhotosSection, purchaseUnitOptions: options.workspace.dropdownData.purchaseUnitOptions, receiptDraftByStep: options.state.receiptDraftByStep, receiptEditorOpenByStep: options.state.receiptEditorOpenByStep,
    receiptEditorRefByStepId: options.state.receiptEditorRefByStepId, receiptRowRefByDocId: options.state.receiptRowRefByDocId, recoveryJobId: options.state.recoveryJobId, recoveryPolling: options.state.recoveryPolling, recoveryReportJson: options.state.recoveryReportJson, recoveryReportOpen: options.state.recoveryReportOpen,
    recoveryStagedCount: options.state.recoveryStagedCount, recoveryStagedRoot: options.state.recoveryStagedRoot, recoveryStatus: options.state.recoveryStatus, refreshingActualCostByStepId: options.state.refreshingActualCostByStepId, renderDocumentGallery: options.actions.renderers.renderDocumentGallery, replaceFileInputByDocId: options.state.replaceFileInputByDocId, replacingDocumentId: options.state.replacingDocumentId,
    savePhaseDateRange: options.buildWizard.savePhaseDateRange, saving: options.buildWizard.saving, savingNoteId: options.state.savingNoteId, selectableDocSteps: options.workspace.workspaceSelectionData.selectableDocSteps, selectedContactAssignments: options.workspace.workspaceData.selectedContactAssignments, selectedDeskContact: options.workspace.workspaceData.selectedDeskContact, setActiveTab: options.state.setActiveTab, setAiToolsOpen: options.state.setAiToolsOpen,
    setAttachExistingDocByReceiptId: options.state.setAttachExistingDocByReceiptId, setAttachExistingDocByStepId: options.state.setAttachExistingDocByStepId, setAttachExistingDocFilterByReceiptId: options.state.setAttachExistingDocFilterByReceiptId, setAttachExistingDocFilterByStepId: options.state.setAttachExistingDocFilterByStepId,
    setAttachExistingPickerOpenByStepId: options.state.setAttachExistingPickerOpenByStepId, setDependencyCandidateByStepId: options.state.setDependencyCandidateByStepId, setDeskAssignmentPhaseKey: options.state.setDeskAssignmentPhaseKey, setDeskAssignmentStepId: options.state.setDeskAssignmentStepId,
    setDeskContactDraft: options.state.setDeskContactDraft, setDeskContactQuery: options.state.setDeskContactQuery, setDeskContactTypeFilter: options.state.setDeskContactTypeFilter, setDeskCreateMode: options.state.setDeskCreateMode, setDeskSelectedContactId: options.state.setDeskSelectedContactId, setDocKind: options.state.setDocKind, setDocPhaseKey: options.state.setDocPhaseKey,
    setDocStepId: options.state.setDocStepId, setDocumentManagerKindFilter: options.state.setDocumentManagerKindFilter, setDocumentManagerPhaseFilter: options.state.setDocumentManagerPhaseFilter, setDocumentManagerQuery: options.state.setDocumentManagerQuery, setDocumentManagerStepFilter: options.state.setDocumentManagerStepFilter,
    setDocumentUploadBusy: options.state.setDocumentUploadBusy, setDocumentUploadFile: options.state.setDocumentUploadFile, setDocumentUploadModalOpen: options.state.setDocumentUploadModalOpen, setDragOverInsertIndex: options.state.setDragOverInsertIndex, setDragOverParentStepId: options.state.setDragOverParentStepId,
    setEditingNoteTextById: options.state.setEditingNoteTextById, setEditingReceiptDocumentIdByStep: options.state.setEditingReceiptDocumentIdByStep, setExpandedStepById: options.state.setExpandedStepById, setInlineReceiptDraftByDocId: options.state.setInlineReceiptDraftByDocId, setLightboxSpreadsheetSheetIndex: options.state.setLightboxSpreadsheetSheetIndex,
    setLotSizeInput: options.state.setLotSizeInput, setMoveStepModalStepId: options.state.setMoveStepModalStepId, setMoveStepModalTargetTab: options.state.setMoveStepModalTargetTab, setMoveTaskModalDocId: options.state.setMoveTaskModalDocId, setMoveTaskModalTargetStepId: options.state.setMoveTaskModalTargetStepId,
    setNoteDraftByStep: options.state.setNoteDraftByStep, setNoteEditorOpenByStep: options.state.setNoteEditorOpenByStep, setProjectDeskOpen: options.state.setProjectDeskOpen, setProjectDraft: options.state.setProjectDraft, setProjectOverviewOpen: options.state.setProjectOverviewOpen, setReceiptAttachmentDraftByStep: options.state.setReceiptAttachmentDraftByStep,
    setReceiptDraftByStep: options.state.setReceiptDraftByStep, setReceiptEditorOpenByStep: options.state.setReceiptEditorOpenByStep, setRecoveryJobId: options.state.setRecoveryJobId, setRecoveryPolling: options.state.setRecoveryPolling, setRecoveryReportJson: options.state.setRecoveryReportJson, setRecoveryReportOpen: options.state.setRecoveryReportOpen,
    setRecoveryStatus: options.state.setRecoveryStatus, setStepCardAssigneeIdFilter: options.state.setStepCardAssigneeIdFilter, setStepCardAssigneeTypeFilter: options.state.setStepCardAssigneeTypeFilter, setStepCardTextFilter: options.state.setStepCardTextFilter, setStepContactCandidateByStepId: options.state.setStepContactCandidateByStepId,
    setStepContactPickerOpenByStepId: options.state.setStepContactPickerOpenByStepId, setStepInfoModalStepId: options.state.setStepInfoModalStepId, setTaskAttachmentsModalDocId: options.state.setTaskAttachmentsModalDocId, setTopbarSearchOpen: options.state.setTopbarSearchOpen, setTopbarSearchQuery: options.state.setTopbarSearchQuery,
    stepById: options.workspace.workspaceData.stepById, stepByIdMap: options.workspace.workspaceData.stepByIdMap, stepCardAssigneeIdFilter: options.state.stepCardAssigneeIdFilter, stepCardAssigneeTypeFilter: options.state.stepCardAssigneeTypeFilter, stepCardTextFilter: options.state.stepCardTextFilter, stepDrafts: options.state.stepDrafts, stepEditModalDependencyIds: options.workspace.stepEditModalDependencyIds,
    stepEditModalDependencyOptions: options.workspace.stepEditModalDependencyOptions, stepEditModalDraft: options.workspace.workspaceData.stepEditModalDraft, stepEditModalStep: options.workspace.workspaceData.stepEditModalStep, stepEditSaving: options.state.stepEditSaving, stepInfoModalStep: options.workspace.workspaceData.stepInfoModalStep, stepPhaseBucket: options.stepPhaseBucket, steps: options.buildWizard.steps,
    stepUiActions: options.actions.stepUiActions, stepWorkspaceMeta: options.workspace.stepWorkspaceMeta, stickyHeadHeight: options.state.stickyHeadHeight, stickyHeadRef: options.state.stickyHeadRef, stickyTopOffset: options.state.stickyTopOffset, taskTypeOptions: TASK_TYPE_OPTIONS,
    taskUsesManualDateOverride: options.taskUsesManualDateOverride, toNumberOrNull: options.toNumberOrNull, toStringOrNull: options.toStringOrNull, toggleStep: options.buildWizard.toggleStep, topbarSearchBoxRef: options.state.topbarSearchBoxRef, topbarSearchLoading: options.state.topbarSearchLoading, topbarSearchOpen: options.state.topbarSearchOpen,
    topbarSearchQuery: options.state.topbarSearchQuery, updateProject: options.buildWizard.updateProject, uploadDocument: options.buildWizard.uploadDocument, verifiedActualCostSignatureByStepId: options.state.verifiedActualCostSignatureByStepId, workflowActions: options.actions.workflowActions, workspaceSelectionData: options.workspace.workspaceSelectionData, workspaceUiCallbacks: options.actions.workspaceUiCallbacks,
  }));
}
