import React from 'react';

import { BuildWizardWorkspaceMain } from './buildWizardWorkspaceMain';

export function useBuildWizardWorkspaceMainPropsBuilder(options: any): React.ComponentProps<typeof BuildWizardWorkspaceMain> {
  return React.useMemo(() => ({
    activeTab: options.activeTab,
    activeTabStepNumbers: options.activeTabStepNumbers,
    chromeProps: {
      activePhaseDateRange: options.activePhaseDateRange,
      activePhaseHasStoredDateRange: options.activePhaseHasStoredDateRange,
      activeTab: options.activeTab,
      buildEntryPoint: options.buildEntryPoint,
      formatCurrency: options.formatCurrency,
      isTemplateProject: options.isTemplateProject,
      onAddStep: () => options.addStep(options.TAB_DEFAULT_PHASE_KEY[options.activeTab] || 'general'),
      onBackFromWorkspace: options.onBackFromWorkspace,
      onCloseWizard: options.onCloseWizard,
      onOpenAiTools: () => options.setAiToolsOpen(true),
      onOpenProjectDesk: () => options.setProjectDeskOpen(true),
      onOpenProjectOverview: () => options.setProjectOverviewOpen(true),
      onPhaseDateRangeChange: options.onPhaseDateRangeChange,
      onResetFilters: () => {
        options.setStepCardAssigneeTypeFilter('all');
        options.setStepCardAssigneeIdFilter(0);
        options.setStepCardTextFilter('');
      },
      onSaveTemplate: options.onSaveTemplate,
      onSelectTab: options.setActiveTab,
      onSetStepCardAssigneeIdFilter: options.setStepCardAssigneeIdFilter,
      onSetStepCardAssigneeTypeFilter: options.setStepCardAssigneeTypeFilter,
      onSetStepCardTextFilter: options.setStepCardTextFilter,
      onTopbarSearchQueryChange: options.setTopbarSearchQuery,
      onTopbarSearchSelect: options.selectTopbarSearchResult,
      onTopbarSearchToggle: options.setTopbarSearchOpen,
      phaseTotals: options.phaseTotals,
      project: options.project,
      projectId: options.projectId,
      savePhaseDateRange: options.savePhaseDateRange,
      saving: options.saving,
      stepCardAssigneeIdFilter: options.stepCardAssigneeIdFilter,
      stepCardAssigneeTypeFilter: options.stepCardAssigneeTypeFilter,
      stepCardTextFilter: options.stepCardTextFilter,
      stepCardTextFilterTokens: options.stepCardTextFilterTokens,
      stepFilterContactOptions: options.stepFilterContactOptions,
      stickyHeadHeight: options.stickyHeadHeight,
      stickyHeadRef: options.stickyHeadRef,
      topbarSearchBoxRef: options.topbarSearchBoxRef,
      topbarSearchLoading: options.topbarSearchLoading,
      topbarSearchOpen: options.topbarSearchOpen,
      topbarSearchQuery: options.topbarSearchQuery,
      topbarSearchResults: options.topbarSearchResults,
    },
    completedSectionProps: {
      completedSteps: options.completedSteps,
      contactTypeChipClass: options.contactTypeChipClass,
      contactTypeLabel: options.contactTypeLabel,
      footerRange: options.footerRange,
      formatCurrency: options.formatCurrency,
      formatDate: options.formatDate,
      normalizeContactType: options.normalizeContactType,
      noteEditedAtLabel: options.noteEditedAtLabel,
      stepAssigneesByStepId: options.stepAssigneesByStepId,
      stepCostTotalExcludingQuotes: options.stepCostTotalExcludingQuotes,
    },
    deskWorkspaceProps: {
      contactsProps: {
        contacts: options.deskContacts,
        contactAssignmentCountById: options.deskContactAssignmentCountById,
        deleteContactAssignment: options.deleteContactAssignment,
        deskAssignmentPhaseKey: options.deskAssignmentPhaseKey,
        deskAssignmentStepId: options.deskAssignmentStepId,
        deskContactDraft: options.deskContactDraft,
        deskContactQuery: options.deskContactQuery,
        deskContactTypeFilter: options.deskContactTypeFilter,
        deskSelectedContactId: options.deskSelectedContactId,
        filteredContacts: options.filteredDeskContacts,
        linkedStepOptions: options.linkedStepOptions,
        onAddDeskPhaseAssignment: options.onAddDeskPhaseAssignment,
        onAddDeskStepAssignment: options.onAddDeskStepAssignment,
        onDeleteDeskContact: options.onDeleteDeskContact,
        onSaveDeskContact: options.onSaveDeskContact,
        onStartNewDeskContact: options.onStartNewDeskContact,
        phaseOptions: options.phaseOptions,
        projectId: options.projectId,
        selectedContact: options.selectedDeskContact,
        selectedContactAssignments: options.selectedContactAssignments,
        setDeskAssignmentPhaseKey: options.setDeskAssignmentPhaseKey,
        setDeskAssignmentStepId: options.setDeskAssignmentStepId,
        setDeskContactDraft: options.setDeskContactDraft,
        setDeskContactQuery: options.setDeskContactQuery,
        setDeskContactTypeFilter: options.setDeskContactTypeFilter,
        setDeskCreateMode: options.setDeskCreateMode,
        setDeskSelectedContactId: options.setDeskSelectedContactId,
        stepByIdMap: options.stepByIdMap,
      },
      documentsProps: {
        buildDocumentDraft: options.buildDocumentDraft,
        deletingDocumentId: options.deletingDocumentId,
        docKindOptions: options.docKindOptions,
        documentManagerKindFilter: options.documentManagerKindFilter,
        documentManagerKindOptions: options.documentManagerKindOptions,
        documentManagerLinkedStepFilterOptions: options.documentManagerLinkedStepFilterOptions,
        documentManagerPhaseFilter: options.documentManagerPhaseFilter,
        documentManagerPhaseOptions: options.documentManagerPhaseOptions,
        documentManagerQuery: options.documentManagerQuery,
        documentManagerSearchLoading: options.documentManagerSearchLoading,
        documentManagerSearchResultById: options.documentManagerSearchResultById,
        documentManagerStepFilter: options.documentManagerStepFilter,
        documentSavingId: options.documentSavingId,
        documents: options.documents,
        filteredDocumentManagerDocs: options.filteredDocumentManagerDocs,
        isPlanPreviewDoc: options.isPlanPreviewDoc,
        isSpreadsheetPreviewDoc: options.isSpreadsheetPreviewDoc,
        linkedStepOptions: options.linkedStepOptions,
        onDeleteDocument: options.onDeleteDocument,
        onOpenUploadModal: () => options.setDocumentUploadModalOpen(true),
        onReplaceDocumentFile: options.onReplaceDocumentFile,
        onSaveDocumentDraft: options.onSaveDocumentDraft,
        openDocumentPreview: options.openDocumentPreview,
        project: options.project,
        replaceFileInputByDocId: options.replaceFileInputByDocId,
        replacingDocumentId: options.replacingDocumentId,
        setDocumentManagerKindFilter: options.setDocumentManagerKindFilter,
        setDocumentManagerPhaseFilter: options.setDocumentManagerPhaseFilter,
        setDocumentManagerQuery: options.setDocumentManagerQuery,
        setDocumentManagerStepFilter: options.setDocumentManagerStepFilter,
        steps: options.steps,
        updateDocumentDraft: options.updateDocumentDraft,
        updateProject: options.updateProject,
      },
      onAddStep: () => options.addStep('general'),
      onClose: () => options.setProjectDeskOpen(false),
      open: options.projectDeskOpen,
      projectDeskSteps: options.projectDeskSteps,
      renderEditableStepCards: options.renderEditableStepCards,
    },
    docKind: options.docKind,
    docKindOptions: options.docKindOptions,
    docPhaseKey: options.docPhaseKey,
    docStepId: options.docStepId,
    documents: options.documents,
    filteredTabSteps: options.filteredTabSteps,
    footerRange: options.footerRange,
    footerTimelineSteps: options.footerTimelineSteps,
    onSetDocKind: options.setDocKind,
    onSetDocPhaseKey: options.setDocPhaseKey,
    onSetDocStepId: options.setDocStepId,
    onTimelineStepChange: options.onTimelineStepChange,
    onUploadDocument: (file: File) => {
      void options.uploadDocument(options.docKind, file, options.docStepId > 0 ? options.docStepId : undefined, undefined, options.docPhaseKey);
    },
    overviewSectionProps: {
      aiBusy: options.aiBusy,
      focusNextStep: (step: any) => options.focusStepInBuildView(options.stepPhaseBucket(step), step.id),
      formatCurrency: options.formatCurrency,
      formatDate: options.formatDate,
      formatTimelineDate: options.formatTimelineDate,
      onEstimateMissingWithAi: options.onEstimateMissingWithAi,
      overviewMetrics: options.overviewMetrics,
      projectPhotosSection: options.projectPhotosSection,
    },
    phaseOptions: options.phaseOptions,
    phaseTaskListCardRef: options.phaseTaskListCardRef,
    renderDocumentGallery: options.renderDocumentGallery,
    renderEditableStepCards: options.renderEditableStepCards,
    selectableDocSteps: options.selectableDocSteps,
    startSectionProps: {
      changeCurrencyEdit: options.changeCurrencyEdit,
      finishCurrencyEdit: options.finishCurrencyEdit,
      formatCurrency: options.formatCurrency,
      lotSizeDetectedUnit: options.lotSizeDetectedUnit,
      lotSizeInput: options.lotSizeInput,
      lotSizeInputToSqftAuto: options.lotSizeInputToSqftAuto,
      projectDraft: options.projectDraft,
      projectPhotosSection: options.projectPhotosSection,
      projectTotals: options.projectTotals,
      renderCurrencyInputValue: options.renderCurrencyInputValue,
      setLotSizeInput: options.setLotSizeInput,
      setProjectDraft: options.setProjectDraft,
      startCurrencyEdit: options.startCurrencyEdit,
      toNumberOrNull: options.toNumberOrNull,
      toStringOrNull: options.toStringOrNull,
      updateProject: options.updateProject,
    },
    stickyTopOffset: options.stickyTopOffset,
  }), [options]);
}
