<?php
declare(strict_types=1);

$kidSignatureAdj = [
    'brass', 'copper', 'silver', 'weathered', 'polished', 'tiny', 'bright', 'faded',
    'striped', 'checkered', 'plain', 'floral', 'ink-stained', 'threadbare', 'neatly-folded', 'scuffed',
    'minty', 'cinnamon', 'smoky', 'soapy', 'pine', 'lemon', 'vanilla', 'coffee',
    'lucky', 'odd', 'stubborn', 'quiet', 'careful', 'bold', 'jumpy', 'patient',
    'pocket', 'worn', 'smooth', 'rough', 'warm', 'cool', 'heavy', 'light',
];

$kidSignatureNoun = [
    'keychain', 'ring', 'coin', 'button', 'pen', 'notebook', 'handkerchief', 'comb',
    'matchbook', 'ticket stub', 'little photo', 'bracelet', 'watch', 'lighter', 'thimble', 'bookmark',
    'stone', 'charm', 'pin', 'patch', 'paperclip', 'rubber band', 'string bracelet', 'postcard',
    'pocketknife', 'seashell', 'bead', 'medallion', 'dice', 'origami crane', 'tiny flashlight', 'map',
];

$kidMore = [
    'Who is one person you trust the most?',
    'If you had a whole free day, what would you do?',
    'What is your favorite meal to eat?',
    'What is your least favorite food?',
    'Are you more of a morning person or a night person?',
    'What is something you are really good at?',
    'What is something you wish you were better at?',
    'What is your favorite holiday?',
    'What is your favorite season of the year?',
    'What is the nicest compliment you remember getting?',
    'What is something that makes you laugh?',
    'What is something that makes you annoyed?',
    'If you could learn one new skill instantly, what would it be?',
    'What is your favorite board game or card game?',
    'Do you like surprises or not?',
    'What is your favorite place to sit and think?',
    'Do you like to be around lots of people or just a few?',
    'If you could have any job for one day, what would you try?',
    'What is your favorite animal?',
    'What animal would you NOT want to meet in a dark alley?',
    'Do you like cooking? Why or why not?',
    'What is your favorite smell in the kitchen?',
    'Do you like to keep your home neat or messy?',
    'What is one rule you always follow?',
    'What is one rule you think is silly?',
    'Do you like to plan ahead or decide last minute?',
    'What is something you always carry with you?',
    'What is your favorite thing you own?',
    'What is something you lost that you still miss?',
    'Do you have a lucky charm or lucky habit?',
    'What is your favorite kind of weather?',
    'Do you like thunderstorms?',
    'What is your favorite kind of movie?',
    'What is a movie you have seen too many times?',
    'What is your favorite TV show or radio program?',
    'What is your favorite song right now?',
    'Do you sing in the car (or when alone)?',
    'What is your favorite book (or kind of book)?',
    'Do you read the news? Where do you get it?',
    'What is your favorite subject to talk about?',
    'What subject do you avoid talking about?',
    'If you had to teach a class, what would you teach?',
    'What is the best advice you ever got?',
    'What is advice you ignore even though it is good?',
    'Do you like sports? Which ones?',
    'Do you like watching sports or playing sports?',
    'What is your favorite way to relax?',
    'Do you fidget when you are nervous?',
    'What do you do when you cannot fall asleep?',
    'Do you like silence or background noise?',
    'What is your favorite sound?',
    'What sound do you hate?',
    'What is your favorite thing about where you live?',
    'What is one thing you would change about your town?',
    'Where would you go on a dream vacation?',
    'What is the last place you traveled to?',
    'Do you like museums? Which kind?',
    'Do you like going to the library?',
    'What is your favorite kind of store to browse?',
    'Do you like to shop or do you avoid it?',
    'What is something you collect (even if it is small)?',
    'What is your favorite kind of candy?',
    'What is your favorite dessert?',
    'Do you like spicy food?',
    'Do you drink coffee or tea?',
    'How do you take your coffee/tea?',
    'What is your favorite breakfast?',
    'What is your favorite thing to eat late at night?',
    'What is a smell that brings back memories?',
    'Do you have a favorite piece of clothing?',
    'What shoes do you wear most often?',
    'Do you prefer fancy clothes or comfy clothes?',
    'What is a habit you are trying to break?',
    'What is a habit you are proud of?',
    'Are you usually early, on time, or late?',
    'What is the most annoying chore?',
    'What chore do you secretly enjoy?',
    'Do you like plants? Do you keep any?',
    'Do you like candles or not?',
    'What is your favorite thing to do on weekends?',
    'What is the best day you had this month?',
    'What is something that happened recently that surprised you?',
    'Who is the funniest person you know?',
    'Who is the most stubborn person you know?',
    'Do you like to work alone or with people?',
    'What is a job you would never want?',
    'What is your biggest pet peeve?',
    'Do you like puzzles or riddles?',
    'Can you whistle?',
    'Do you have a signature phrase you say a lot?',
    'Do you prefer phone calls or texts?',
    'Do you like to drive?',
    'What is your favorite kind of car (or vehicle)?',
    'Do you get carsick?',
    'Do you like heights?',
    'Do you like water (swimming/boats)?',
    'What is your favorite kind of sandwich?',
    'If you could have a superpower, what would it be?',
    'If you could talk to animals, what would you ask them?',
    'Do you like being the center of attention?',
    'Do you blush easily?',
    'What is something that always cheers you up?',
    'What is something that always puts you in a bad mood?',
    'What is something you cannot stand waiting for?',
    'What is something you could wait for all day?',
    'Do you like fireworks?',
    'Do you like roller coasters?',
    'What is your favorite smell outside?',
    'Do you like the beach or the mountains more?',
    'What is your favorite thing about nighttime?',
    'What is your favorite thing about daytime?',
    'Do you like to keep secrets?',
    'Do you forgive easily?',
    'Do you hold grudges?',
    'What is something you are proud of doing?',
    'What is something you regret doing?',
    'Do you like to apologize quickly or think first?',
    'What is the best gift you ever got?',
    'What is the best gift you ever gave?',
    'Do you like to talk when you are nervous?',
    'Do you like to sit still or move around?',
    'What is your favorite kind of cookie?',
    'What is your favorite ice cream flavor?',
    'What is the best sandwich topping?',
    'What is your favorite pizza topping?',
    'If you had to eat one food forever, what would it be?',
    'If you could throw away one food forever, what would it be?',
    'What is something you do when you are bored?',
    'What is your favorite park (or outdoor spot) near here?',
    'Do you like to go fishing?',
    'Do you like camping?',
    'What is your favorite way to spend a rainy day?',
    'What is your favorite kind of party game?',
    'Do you like karaoke?',
    'What is one thing you are always losing?',
    'What is one thing you never lose?',
    'Do you like to write things down or remember them?',
    'What is your favorite type of pen/pencil?',
    'Do you like calendars or do you ignore them?',
    'What is your favorite kind of snack to share?',
    'Do you like to share food or keep your plate to yourself?',
    'What is your favorite kind of soup?',
    'Do you like to dance?',
    'What is your favorite thing to do at a fair?',
    'What is your favorite ride?',
    'What is your favorite smell in a store?',
    'What is one thing you notice first about a room?',
    'Do you like bright lights or dim lights?',
    'Do you prefer doors open or closed?',
    'Do you like to sit near a window?',
    'Do you like meeting new people?',
    'What is your favorite way to say hello?',
    'Do you like hugging or handshakes?',
    'What is a compliment you like to hear?',
    'Do you like to brag or stay quiet?',
    'What is something you are secretly competitive about?',
    'What is something you would do if nobody could judge you?',
    'What is your favorite kind of cereal?',
    'What is your favorite fruit?',
    'What is your favorite vegetable?',
    'Do you like spicy chips?',
    'Do you like sour candy?',
    'What is your favorite kind of cake?',
    'What is your favorite kind of pie?',
    'Do you like donuts?',
    'What is your favorite donut?',
    'What is your favorite holiday food?',
    'Do you like telling stories?',
    'What story do you tell the most?',
    'Do you like jokes? What kind?',
    'What is a joke you always remember?',
    'Do you like to be interrupted or do you hate it?',
    'What is your favorite seat in a car?',
    'Do you like to ride in silence or talk?',
    'What is a smell you dislike?',
    'What is your favorite kind of shampoo/soap smell?',
    'Do you like mint or cinnamon more?',
    'Do you like to work with your hands?',
    'Do you like to fix things or replace them?',
    'What is something you can fix without looking up a tutorial?',
    'What is something you cannot fix at all?',
    'Do you like to take photos?',
    'What do you usually take photos of?',
    'Do you like to keep souvenirs?',
    'What souvenir would you keep from a perfect day?',
    'Do you like to keep your inbox clean or messy?',
    'Do you like lists?',
    'Do you like routines or new experiences?',
    'What is your favorite kind of sandwich bread?',
    'Do you like crunchy snacks or soft snacks?',
    'What is your favorite sound at home?',
    'What is your favorite smell at home?',
    'Do you like to open windows or keep them closed?',
    'Do you like fans or air conditioning?',
    'What is your favorite thing to do after work?',
    'What is your favorite kind of cake frosting?',
    'Do you like chocolate or vanilla more?',
    'What is your favorite way to eat eggs?',
    'Do you like pancakes or waffles more?',
    'Do you like syrup or no syrup?',
    'What is your favorite jam/jelly?',
    'What is your favorite thing to eat with fries?',
    'Do you like pickles?',
    'What is your favorite kind of pickle?',
    'What is a smell you associate with safety?',
    'What is a smell you associate with trouble?',
    'Do you like to sit in the front row or back row?',
    'Do you like elevators or stairs?',
    'Do you like reading menus or ordering the same thing?',
    'What is your favorite restaurant type?',
    'Do you like to tip extra or just normal?',
    'Do you like to negotiate prices or pay and go?',
    'Do you like to talk to strangers?',
    'Do you like small talk?',
    'What is your favorite kind of compliment to give?',
    'Do you like being asked lots of questions?',
    'Do you like to answer quickly or think a long time?',
    'If you could redo one day, which day would you pick?',
    'If you could fast-forward one week, would you?',
    'Do you like fireworks from far away or up close?',
    'Do you like the smell of gasoline or hate it?',
    'Do you like the smell of a new book?',
    'Do you like the smell of fresh cut grass?',
    'Do you like being barefoot indoors?',
    'Do you like socks?',
    'Do you like hats?',
    'What kind of hat would you wear?',
];
