import React from 'react';

export interface MasterAssetDetailsModalProps {
  modalRef: React.RefObject<HTMLDivElement>;
  busy: boolean;
  isAdmin: boolean;
  masterAssetDetailsItem: any;
  masterAssetDetailsType: string;
  masterAssetDetailsName: string;
  setMasterAssetDetailsName: (val: string) => void;
  masterAssetDetailsSlug: string;
  setMasterAssetDetailsSlug: (val: string) => void;
  masterAssetDetailsFields: any;
  setMasterAssetDetailsFields: React.Dispatch<React.SetStateAction<any>>;
  masterAssetDetailsRapport: any;
  setMasterAssetDetailsRapport: React.Dispatch<React.SetStateAction<any>>;
  masterAssetDetailsFavorites: any;
  setMasterAssetDetailsFavorites: React.Dispatch<React.SetStateAction<any>>;
  voiceProfiles: any[];
  isMasterAssetDetailsDirty: boolean;
  masterCharacterImageUrl: string;
  masterCharacterMugshotUrl: string;
  masterCharacterIrUrls: string[];
  masterCharacterIrIndex: number;
  setMasterCharacterIrIndex: React.Dispatch<React.SetStateAction<number>>;
  masterCharacterIrEmotions: string[];
  masterCharacterIrEmotionEnabled: Record<string, boolean>;
  setMasterCharacterIrEmotionEnabled: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  masterCharacterMissingRequiredImageFields: string[];
  loadMasterCharacterDeposition: () => Promise<void>;
  masterCharacterDepositionText: string;
  masterCharacterDepositionUpdatedAt: string;
  masterCharacterDepositionError: string;
  masterCharacterDepositionBusy: boolean;
  scenarioId: string | number;
  caseId: string | number;
  masterCharacterScenarioEntityId: number | null;
  enqueueSpecificJob: (params: { action: string; spec: any; requireScenario: boolean; entityId?: any }) => Promise<void>;
  openJsonPreview: (opts: { title: string; payload: any }) => void;
  saveMasterAssetDetails: () => Promise<void>;
  generateMasterAssetContent: () => Promise<void>;
  clearMasterAssetFields: () => void;
  openMasterAssetDerivedJson: () => void;
  updateMasterAssetDetailsDataObject: (updater: any) => void;
  toggleMasterAssetFieldLock: (field: string) => void;
  isMasterAssetFieldLocked: (field: string) => boolean;
  onOpenAiImageConfig: () => void;
  uploadMasterCharacterImage: (opts: { kind: 'character' | 'mugshot' | 'ir'; file: File }) => Promise<void>;
  deleteMasterCharacterImage: (opts: { kind: 'character' | 'mugshot' | 'ir'; url?: string }) => Promise<void>;
  openMasterCharacterImagePrompt: (opts: { kind: 'character' | 'mugshot' | 'ir' }) => Promise<void>;
  generateMasterCharacterImages: (opts: { kind: 'character' | 'mugshot' | 'ir' }) => Promise<void>;
  generateAllMissingMasterCharacterImages: () => Promise<void>;
  uploadMasterAssetImage: (opts: { file: File }) => Promise<void>;
  generateMasterAssetPrimaryImage: () => Promise<void>;
  deleteMasterAssetPrimaryImage: () => Promise<void>;
  archiveMasterAsset: (opts: { type: string; id: string | number; is_archived: number }) => Promise<void>;
  resetMasterAssetDetails: () => void;
  getMasterAssetDataObject: () => any;
  masterAssetDetailsDataText: string;
  saveSvg: React.ReactNode;
  cogSvg: React.ReactNode;
  lockSvg: React.ReactNode;
  unlockSvg: React.ReactNode;
  trashSvg: React.ReactNode;
  pencilSvg: React.ReactNode;
}
