import { DateRangeFilter, LedgerFilterPreset } from './accumul8PageTypes';

export function buildAccumul8SecondaryTabProps(options: any) {
  return {
    ledgerTabProps: {
      activeLedgerRowId: options.activeLedgerRowId,
      activateLedgerRow: options.activateLedgerRow,
      beginEditTransaction: options.beginEditTransaction,
      beginViewTransaction: options.beginViewTransaction,
      busy: options.busy,
      customLedgerEndDate: options.customLedgerEndDate,
      customLedgerStartDate: options.customLedgerStartDate,
      filterPresetOptions: options.LEDGER_FILTER_PRESET_OPTIONS,
      flashingSaveButtonKey: options.flashingSaveButtonKey,
      getAccountDisplayName: options.getAccountDisplayName,
      handleDeleteTransaction: options.handleDeleteTransaction,
      ledgerDateFilter: options.ledgerDateFilter,
      ledgerDisplayBalanceById: options.ledgerDisplayBalanceById,
      ledgerDraftById: options.ledgerDraftById,
      ledgerFilterPreset: options.ledgerFilterPreset,
      ledgerPagination: options.ledgerPagination,
      ledgerPaginationMode: options.ledgerPaginationMode,
      ledgerTable: options.ledgerTable,
      ledgerTableRef: options.ledgerTableRef,
      listSearchQuery: options.listSearchQueryByTab.ledger,
      openCreateTransactionModal: options.openCreateTransactionModal,
      openLedgerEntityModal: options.openLedgerEntityModal,
      renderDateRangeControls: options.renderDateRangeControls,
      saveLedgerRow: options.saveLedgerRow,
      setCustomLedgerEndDate: options.setCustomLedgerEndDate,
      setCustomLedgerStartDate: options.setCustomLedgerStartDate,
      setInlineRowRef: options.setInlineRowRef,
      setLedgerArchivePage: options.setLedgerArchivePage,
      setLedgerDateFilter: (value: string) => options.setLedgerDateFilter(value as DateRangeFilter),
      setLedgerFilterPreset: (value: string) => options.setLedgerFilterPreset(value as LedgerFilterPreset),
      setLedgerPaginationMode: options.setLedgerPaginationMode,
      setLedgerRowDraft: options.setLedgerRowDraft,
      setListSearchQuery: (value: string) => options.setListSearchQueryByTab((prev: any) => ({ ...prev, ledger: value })),
    },
    notificationsTabProps: {
      beginEditNotificationRule: options.beginEditNotificationRule,
      busy: options.busy,
      createNotificationRule: options.createNotificationRule,
      deleteNotificationRule: options.deleteNotificationRule,
      editingNotificationRuleId: options.editingNotificationRuleId,
      notificationForm: options.notificationForm,
      notificationRules: options.notificationRules,
      parseCustomUserIds: options.parseCustomUserIds,
      resetNotificationForm: options.resetNotificationForm,
      sendNotification: options.sendNotification,
      setNotificationForm: options.setNotificationForm,
      toggleNotificationRule: options.toggleNotificationRule,
      updateNotificationRule: options.updateNotificationRule,
    },
    payBillsTabProps: {
      activatePayBillRow: options.activatePayBillRow,
      activeOwnerUserId: options.activeOwnerUserId,
      activePayBillRowId: options.activePayBillRowId,
      beginViewTransaction: options.beginViewTransaction,
      busy: options.busy,
      customPayBillsEndDate: options.customPayBillsEndDate,
      customPayBillsStartDate: options.customPayBillsStartDate,
      deleteTransaction: options.deleteTransaction,
      flashingSaveButtonKey: options.flashingSaveButtonKey,
      getAccountDisplayName: options.getAccountDisplayName,
      listSearchQuery: options.listSearchQueryByTab.pay_bills,
      openLedgerEntityModal: options.openLedgerEntityModal,
      payBillsAccountOptions: options.payBillsAccountOptions,
      payBillsDateFilter: options.payBillsDateFilter,
      payBillsTable: options.payBillsTable,
      payBillsTableRef: options.payBillsTableRef,
      payBillDraftById: options.payBillDraftById,
      renderDateRangeControls: options.renderDateRangeControls,
      savePayBillRow: options.savePayBillRow,
      selectedOwnerUserId: options.selectedOwnerUserId,
      setCustomPayBillsEndDate: options.setCustomPayBillsEndDate,
      setCustomPayBillsStartDate: options.setCustomPayBillsStartDate,
      setInlineRowRef: options.setInlineRowRef,
      setListSearchQuery: (value: string) => options.setListSearchQueryByTab((prev: any) => ({ ...prev, pay_bills: value })),
      setPayBillRowDraft: options.setPayBillRowDraft,
      setPayBillsDateFilter: (value: string) => options.setPayBillsDateFilter(value as DateRangeFilter),
      statementUploads: options.statementUploads,
      todayDate: options.todayDate,
    },
    recurringTabProps: {
      activeRecurringRowId: options.activeRecurringRowId,
      beginEditRecurring: options.beginEditRecurring,
      busy: options.busy,
      deleteRecurring: options.deleteRecurring,
      flashingSaveButtonKey: options.flashingSaveButtonKey,
      getAccountDisplayName: options.getAccountDisplayName,
      listSearchQuery: options.listSearchQueryByTab.recurring,
      openCreateRecurringModal: options.openCreateRecurringModal,
      openRecurringLinkModal: options.openRecurringLinkModal,
      payBillsAccountOptions: options.payBillsAccountOptions,
      recurringDraftById: options.recurringDraftById,
      recurringTable: options.recurringTable,
      recurringTableRef: options.recurringTableRef,
      saveRecurringRow: options.saveRecurringRow,
      setInlineRowRef: options.setInlineRowRef,
      setListSearchQuery: (value: string) => options.setListSearchQueryByTab((prev: any) => ({ ...prev, recurring: value })),
      setRecurringRowDraft: options.setRecurringRowDraft,
    },
    spreadsheetViewProps: {
      busy: options.busy,
      selectedMonth: options.budgetMonth,
      recurringPayments: options.budgetPlannerRecurringPayments,
      transactions: options.filteredTransactions,
      entities: options.contactEntities,
      accounts: options.scopedAccounts,
      onSelectedMonthChange: options.setBudgetMonth,
      onEnsureBudgetMonth: async (monthValue: string) => { await options.ensureBudgetMonth({ month_value: monthValue }); },
      onUpdateTransaction: options.updateTransaction,
      onDeleteRecurring: options.handleDeleteRecurring,
      onOpenRecurring: options.beginEditRecurring,
    },
    statementsPanelProps: {
      busy: options.busy,
      accounts: options.accounts,
      bankingOrganizations: options.bankingOrganizations,
      statementUploads: options.statementUploads,
      archivedStatementUploads: options.archivedStatementUploads,
      statementAuditRuns: options.statementAuditRuns,
      transactions: options.transactions,
      ownerUserId: options.selectedOwnerUserId || options.activeOwnerUserId || 0,
      onUpload: options.uploadStatement,
      onRescan: options.rescanStatementUpload,
      onUpdateMetadata: options.updateStatementUploadMetadata,
      onArchiveStatement: options.archiveStatementUpload,
      onRestoreStatement: options.restoreStatementUpload,
      onDeleteArchivedStatement: options.deleteArchivedStatementUpload,
      onConfirmImport: options.confirmStatementImport,
      onReconcile: options.reconcileStatementUpload,
      onImportReviewRow: options.importStatementReviewRow,
      onLinkReviewRow: options.linkStatementReviewRow,
      onSearch: options.searchStatementUploads,
      onAuditStatements: options.auditStatementUploads,
      onAuditImportedCleanup: options.auditImportedTransactionCleanup,
      onPurgeImportedCleanup: options.purgeImportedTransactionCleanup,
      onPurgeAllImportedTransactions: options.purgeAllImportedStatementTransactions,
      onPurgeAllStatementUploads: options.purgeAllStatementUploads,
      onOpenTransaction: options.beginViewTransaction,
      onDeleteTransaction: options.handleDeleteTransaction,
    },
    syncTabProps: {
      bankConnections: options.bankConnections,
      busy: options.busy,
      createBankConnection: options.createBankConnection,
      deleteBankConnection: options.deleteBankConnection,
      formatAccountBackfillNote: options.formatAccountBackfillNote,
      formatAccountMappingLabel: options.formatAccountMappingLabel,
      formatSyncStatusLabel: options.formatSyncStatusLabel,
      formatSyncStatusMessage: options.formatSyncStatusMessage,
      isTellerRateLimited: options.isTellerRateLimited,
      lastSyncReport: options.lastSyncReport,
      linkedAccountsByConnectionId: options.linkedAccountsByConnectionId,
      openSyncHelp: options.openSyncHelp,
      runConnectionSync: options.runConnectionSync,
      runTellerConnect: options.runTellerConnect,
      runTellerReconnect: options.runTellerReconnect,
      summaryFormatAccountBackfillNote: options.formatSyncSummaryBackfillNote,
      summaryFormatAccountLabel: options.formatSyncSummaryAccountLabel,
      syncProvider: options.syncProvider,
      syncingConnectionId: options.syncingConnectionId,
      updateBankConnection: options.updateBankConnection,
    },
    tab: options.tab,
  };
}
