export function buildAccumul8PrimaryTabProps(options: any) {
  return {
    aiPanelProps: {
      ownerUserId: options.selectedOwnerUserId || options.activeOwnerUserId || 0,
      ownerUsername: options.selectedOwnerProfile?.username || options.viewer?.username || 'You',
      runningHousekeeping: options.runningAIcountantHousekeeping,
      balancingBooks: options.balancingBooks,
      runningWatchlist: options.runningAIcountantWatchlist,
      messageBoardPendingCount: options.messageBoardUnacknowledgedCount,
      onRunHousekeeping: options.handleRunAIcountantHousekeeping,
      onBalanceBooks: options.handleBalanceBooks,
      onRunWatchlist: options.handleRunAIcountantWatchlist,
      onOpenMessageBoard: () => options.setMessageBoardOpen(true),
      onDataChanged: options.load,
      onToast: options.onToast,
    },
    calendarViewProps: {
      accounts: options.scopedAccounts,
      transactions: options.filteredTransactions,
      onTransactionSelect: options.beginViewTransaction,
    },
    contactsTabProps: {
      activeEntityRowId: options.activeEntityRowId,
      activateEntityRow: options.activateEntityRow,
      busy: options.busy,
      defaultEntityAliasDraft: options.DEFAULT_ENTITY_ALIAS_DRAFT,
      entities: options.entities,
      entitiesTable: options.entitiesTable,
      entitiesTableRef: options.entitiesTableRef,
      entityAliasDraftById: options.entityAliasDraftById,
      entityDraftById: options.entityDraftById,
      entityTransactionSummaryById: options.entityTransactionSummaryById,
      flashingSaveButtonKey: options.flashingSaveButtonKey,
      listSearchQuery: options.listSearchQueryByTab.contacts,
      openCreateEntityModal: options.openCreateEntityModal,
      removeEntityAlias: options.removeEntityAlias,
      saveEntityAlias: options.saveEntityAlias,
      saveEntityRow: options.saveEntityRow,
      setEntityAliasDraftById: options.setEntityAliasDraftById,
      setEntityHistoryEntityId: options.setEntityHistoryEntityId,
      setEntityRowDraft: options.setEntityRowDraft,
      setInlineRowRef: options.setInlineRowRef,
      setListSearchQuery: (value: string) => options.setListSearchQueryByTab((prev: any) => ({ ...prev, contacts: value })),
    },
    debtorsTabProps: {
      activateDebtorRow: options.activateDebtorRow,
      activeDebtorRowId: options.activeDebtorRowId,
      activeLedgerRowId: options.activeLedgerRowId,
      activeOwnerUserId: options.activeOwnerUserId,
      balanceLedgerTable: options.balanceLedgerTable,
      balanceLedgerTableRef: options.balanceLedgerTableRef,
      beginEditTransaction: options.beginEditTransaction,
      beginViewTransaction: options.beginViewTransaction,
      busy: options.busy,
      debtorDraftById: options.debtorDraftById,
      debtorRunningBalanceByTxId: options.debtorRunningBalanceByTxId,
      debtorsTable: options.debtorsTable,
      debtorsTableRef: options.debtorsTableRef,
      deleteDebtor: options.deleteDebtor,
      flashingSaveButtonKey: options.flashingSaveButtonKey,
      groupedDebtors: options.groupedDebtors,
      handleDeleteTransaction: options.handleDeleteTransaction,
      ledgerDraftById: options.ledgerDraftById,
      listSearchQuery: options.listSearchQueryByTab.debtors,
      openCreateDebtorModal: options.openCreateDebtorModal,
      openCreateIouTransactionModal: options.openCreateIouTransactionModal,
      openLedgerEntityModal: options.openLedgerEntityModal,
      saveDebtorRow: options.saveDebtorRow,
      saveLedgerRow: options.saveLedgerRow,
      selectedDebtorId: options.selectedDebtorId,
      selectedOwnerUserId: options.selectedOwnerUserId,
      setDebtorRowDraft: options.setDebtorRowDraft,
      setInlineRowRef: options.setInlineRowRef,
      setListSearchQuery: (value: string) => options.setListSearchQueryByTab((prev: any) => ({ ...prev, debtors: value })),
      setSelectedDebtorId: options.setSelectedDebtorId,
      statementUploads: options.statementUploads,
    },
    entityEndexTabProps: {
      beginEditEntity: options.beginEditEntity,
      busy: options.busy,
      entityEndexFindingAll: options.entityEndexFindingAll,
      entityEndexGuideByParentKey: options.entityEndexGuideByParentKey,
      entityEndexGuides: options.entityEndexGuides,
      entityEndexParents: options.entityEndexParents,
      entityEndexQuery: options.entityEndexQuery,
      entityEndexScanLogs: options.entityEndexScanLogs,
      entityTransactionSummaryById: options.entityTransactionSummaryById,
      linkedAliasEntitiesByParentId: options.linkedAliasEntitiesByParentId,
      openEntityEndexGuideModal: options.openEntityEndexGuideModal,
      runEntityMaintenanceAliasScan: options.runEntityMaintenanceAliasScan,
      setEntityEndexLogOpen: options.setEntityEndexLogOpen,
      setEntityEndexQuery: options.setEntityEndexQuery,
    },
  };
}
