import React from 'react';

import { useAccumul8PageActionGroupOptions } from './useAccumul8PageActionGroupOptions';
import { useAccumul8PageActionGroups } from './useAccumul8PageActionGroups';

export function useAccumul8PageActionsSetup(options: any) {
  const closeEntityEndexGuideModal = React.useCallback(() => {
    options.setEditingEntityEndexGuideId(null);
    options.setEntityEndexGuideModalOpen(false);
  }, [options.setEditingEntityEndexGuideId, options.setEntityEndexGuideModalOpen]);

  const pageActionGroupOptions = useAccumul8PageActionGroupOptions({
    closeEntityEndexGuideModal,
    contacts: options.contacts,
    createContact: options.createContact,
    createDebtor: options.createDebtor,
    createEntity: options.createEntity,
    createEntityAlias: options.createEntityAlias,
    createEntityEndexGuide: options.createEntityEndexGuide,
    createRecurring: options.createRecurring,
    createTransaction: options.createTransaction,
    DEFAULT_CONTACT_FORM: options.DEFAULT_CONTACT_FORM,
    DEFAULT_ENTITY_ALIAS_DRAFT: options.DEFAULT_ENTITY_ALIAS_DRAFT,
    DEFAULT_ENTITY_FORM: options.DEFAULT_ENTITY_FORM,
    DEFAULT_RECURRING_FORM: options.DEFAULT_RECURRING_FORM,
    debtorDraftById: options.debtorDraftById,
    deleteEntityAlias: options.deleteEntityAlias,
    deleteEntityEndexGuide: options.deleteEntityEndexGuide,
    deleteRecurring: options.deleteRecurring,
    deleteTransaction: options.deleteTransaction,
    editingContactId: options.editingContactId,
    editingDebtorId: options.editingDebtorId,
    editingEntityEndexGuideId: options.editingEntityEndexGuideId,
    editingEntityId: options.editingEntityId,
    editingNotificationRuleId: options.editingNotificationRuleId,
    editingRecurringForm: options.editingRecurringForm,
    editingRecurringId: options.editingRecurringId,
    editingTransactionId: options.editingTransactionId,
    entities: options.entities,
    entityAliasDraftById: options.entityAliasDraftById,
    entityDraftById: options.entityDraftById,
    findAllEntityAliases: options.findAllEntityAliases,
    findEntityAliases: options.findEntityAliases,
    load: options.load,
    notificationRules: options.notificationRules,
    onToast: options.onToast,
    payBillDraftById: options.payBillDraftById,
    recurringDraftById: options.recurringDraftById,
    recurringPayments: options.recurringPayments,
    scopedActionUrl: options.scopedActionUrl,
    selectedBankAccountId: options.selectedBankAccountId,
    setActiveDebtorRowId: options.setActiveDebtorRowId,
    setActiveEntityRowId: options.setActiveEntityRowId,
    setActiveLedgerRowId: options.setActiveLedgerRowId,
    setActivePayBillRowId: options.setActivePayBillRowId,
    setActiveRecurringRowId: options.setActiveRecurringRowId,
    setBudgetForm: options.setBudgetForm,
    setContactForm: options.setContactForm,
    setContactModalOpen: options.setContactModalOpen,
    setDebtorDraftById: options.setDebtorDraftById,
    setDebtorForm: options.setDebtorForm,
    setDebtorModalOpen: options.setDebtorModalOpen,
    setEditingBudgetRowId: options.setEditingBudgetRowId,
    setEditingContactId: options.setEditingContactId,
    setEditingDebtorId: options.setEditingDebtorId,
    setEditingEntityEndexGuideId: options.setEditingEntityEndexGuideId,
    setEditingEntityId: options.setEditingEntityId,
    setEditingNotificationRuleId: options.setEditingNotificationRuleId,
    setEditingRecurringForm: options.setEditingRecurringForm,
    setEditingRecurringId: options.setEditingRecurringId,
    setEditingTransactionId: options.setEditingTransactionId,
    setEntityAliasDraftById: options.setEntityAliasDraftById,
    setEntityDraftById: options.setEntityDraftById,
    setEntityEndexFindingAll: options.setEntityEndexFindingAll,
    setEntityEndexGuideModalOpen: options.setEntityEndexGuideModalOpen,
    setEntityForm: options.setEntityForm,
    setEntityModalOpen: options.setEntityModalOpen,
    setLastSyncReport: options.setLastSyncReport,
    setLedgerDraftById: options.setLedgerDraftById,
    setLedgerEntityModalTransactionId: options.setLedgerEntityModalTransactionId,
    setLedgerForm: options.setLedgerForm,
    setNotificationForm: options.setNotificationForm,
    setPayBillDraftById: options.setPayBillDraftById,
    setRecurringDraftById: options.setRecurringDraftById,
    setRecurringModalOpen: options.setRecurringModalOpen,
    setSyncHelpError: options.setSyncHelpError,
    setSyncHelpOpen: options.setSyncHelpOpen,
    setSyncHelpToken: options.setSyncHelpToken,
    setSyncingConnectionId: options.setSyncingConnectionId,
    setTab: options.setTab,
    setTransactionModalMode: options.setTransactionModalMode,
    setTransactionModalOpen: options.setTransactionModalOpen,
    setTransactionModalVariant: options.setTransactionModalVariant,
    setViewingTransactionId: options.setViewingTransactionId,
    syncBankConnection: options.syncBankConnection,
    syncProvider: options.syncProvider,
    transactions: options.transactions,
    updateContact: options.updateContact,
    updateDebtor: options.updateDebtor,
    updateEntity: options.updateEntity,
    updateEntityEndexGuide: options.updateEntityEndexGuide,
    updateRecurring: options.updateRecurring,
    updateTransaction: options.updateTransaction,
  });

  return useAccumul8PageActionGroups(pageActionGroupOptions);
}
