import { formatAccountOptionLabel, formatCurrencyAmount, formatSummaryWindowLabel } from './accumul8PageDateSearchUtils';
import { getActiveFilterClass, normalizeEntityKind } from './accumul8PageEntityUtils';
import { ACCUMUL8_OWNER_STORAGE_KEY, DEFAULT_ENTITY_ALIAS_DRAFT, LEDGER_FILTER_PRESET_OPTIONS } from './accumul8PageDefaults';
import { formatAccountBackfillNote, formatAccountMappingLabel, formatSyncStatusLabel, formatSyncStatusMessage, formatSyncSummaryAccountLabel, formatSyncSummaryBackfillNote, isTellerRateLimited } from './accumul8PageRecurringSyncUtils';
import { useAccumul8PageComposedProps } from './useAccumul8PageComposedProps';

export function useAccumul8PageCompositionSetup(session: any, state: any, data: any, viewer: any, onToast?: (toast: { tone: 'success' | 'error' | 'info' | 'warning'; message: string }) => void) {
  return useAccumul8PageComposedProps({
    actions: data.pageActions,
    constants: {
      ACCUMUL8_OWNER_STORAGE_KEY,
      DEFAULT_ENTITY_ALIAS_DRAFT,
      LEDGER_FILTER_PRESET_OPTIONS,
      formatAccountBackfillNote,
      formatAccountMappingLabel,
      formatAccountOptionLabel,
      formatCurrencyAmount,
      formatSummaryWindowLabel,
      formatSyncStatusLabel,
      formatSyncStatusMessage,
      formatSyncSummaryAccountLabel,
      formatSyncSummaryBackfillNote,
      getActiveFilterClass,
      isTellerRateLimited,
      normalizeEntityKind,
    },
    data: {
      accessibleAccountOwners: session.accessibleAccountOwners, accounts: session.accounts, activeDebtorRowId: state.activeDebtorRowId, activeEntityRowId: state.activeEntityRowId, activeLedgerRowId: state.activeLedgerRowId,
      activeOwnerUserId: session.activeOwnerUserId, activePayBillRowId: state.activePayBillRowId, activeRecurringRowId: state.activeRecurringRowId, archiveStatementUpload: session.archiveStatementUpload,
      archivedStatementUploads: session.archivedStatementUploads, auditImportedTransactionCleanup: session.auditImportedTransactionCleanup, auditStatementUploads: session.auditStatementUploads,
      bankConnections: session.bankConnections, bankingOrganizations: session.bankingOrganizations, budgetMonth: state.budgetMonth, busy: session.busy, confirmStatementImport: session.confirmStatementImport,
      createAccount: session.createAccount, createBankConnection: session.createBankConnection, createBankingOrganization: session.createBankingOrganization, createNotificationRule: session.createNotificationRule,
      customLedgerEndDate: state.customLedgerEndDate, customLedgerStartDate: state.customLedgerStartDate, customPayBillsEndDate: state.customPayBillsEndDate, customPayBillsStartDate: state.customPayBillsStartDate,
      debtorDraftById: state.debtorDraftById, debtorForm: state.debtorForm, debtorRunningBalanceByTxId: data.debtorPayBillData.debtorRunningBalanceByTxId, deleteAccount: session.deleteAccount,
      deleteArchivedStatementUpload: session.deleteArchivedStatementUpload, deleteBankConnection: session.deleteBankConnection, deleteBankingOrganization: session.deleteBankingOrganization,
      deleteDebtor: session.deleteDebtor, deleteNotificationRule: session.deleteNotificationRule, deleteRecurring: session.deleteRecurring, deleteTransaction: session.deleteTransaction, editingContactId: state.editingContactId,
      editingDebtorId: state.editingDebtorId, editingEntity: data.resolvedEntityData.editingEntity, editingEntityId: state.editingEntityId, editingNotificationRuleId: state.editingNotificationRuleId,
      editingRecurringForm: state.editingRecurringForm, editingRecurringId: state.editingRecurringId, editingTransactionId: state.editingTransactionId, ensureBudgetMonth: session.ensureBudgetMonth,
      entities: session.entities, entitiesSorted: data.entityListData.entitiesSorted,
      entitiesWithResolvedAliases: data.resolvedEntityData.entitiesWithResolvedAliases, entityAliasDraftById: state.entityAliasDraftById, entityDraftById: state.entityDraftById, entityEndexGuides: session.entityEndexGuides,
      entityEndexScanLogs: session.entityEndexScanLogs, entityForm: state.entityForm, groupedDebtors: data.debtorPayBillData.groupedDebtors, headerSummary: data.resolvedEntityData.headerSummary,
      importStatementReviewRow: session.importStatementReviewRow, lastSyncReport: state.lastSyncReport, ledgerDateFilter: state.ledgerDateFilter, ledgerDisplayBalanceById: data.ledgerData.ledgerDisplayBalanceById,
      ledgerDraftById: state.ledgerDraftById, ledgerForm: state.ledgerForm, ledgerPagination: data.ledgerTableData.ledgerPagination, ledgerPaginationMode: state.ledgerPaginationMode,
      ledgerTable: data.ledgerTableData.ledgerTable, linkStatementReviewRow: session.linkStatementReviewRow, load: session.load, notificationForm: state.notificationForm, notificationRules: session.notificationRules,
      onToast, payBillsAccountOptions: data.debtorPayBillData.payBillsAccountOptions, payBillsDateFilter: state.payBillsDateFilter, payBillDraftById: state.payBillDraftById, projectedBalanceForWindow: data.debtorPayBillData.projectedBalanceForWindow,
      purgeImportedTransactionCleanup: session.purgeImportedTransactionCleanup, purgeAllImportedStatementTransactions: session.purgeAllImportedStatementTransactions, purgeAllStatementUploads: session.purgeAllStatementUploads,
      reconcileStatementUpload: session.reconcileStatementUpload, recurringDraftById: state.recurringDraftById, rescanStatementUpload: session.rescanStatementUpload, restoreStatementUpload: session.restoreStatementUpload,
      saveLedgerEntityRule: data.saveLedgerEntityRule, searchStatementUploads: session.searchStatementUploads,
      selectedOwnerUserId: session.selectedOwnerUserId, sendNotification: session.sendNotification, setBudgetMonth: state.setBudgetMonth, setCustomLedgerEndDate: state.setCustomLedgerEndDate,
      setCustomLedgerStartDate: state.setCustomLedgerStartDate, setCustomPayBillsEndDate: state.setCustomPayBillsEndDate, setCustomPayBillsStartDate: state.setCustomPayBillsStartDate,
      setDebtorRowDraft: data.pageActions.setDebtorRowDraft, setEntityAliasDraftById: state.setEntityAliasDraftById, setEntityRowDraft: data.pageActions.setEntityRowDraft, setLedgerArchivePage: state.setLedgerArchivePage, setLedgerDateFilter: state.setLedgerDateFilter,
      setLedgerPaginationMode: state.setLedgerPaginationMode, setLedgerRowDraft: data.pageActions.setLedgerRowDraft, setNotificationForm: state.setNotificationForm, setPayBillsDateFilter: state.setPayBillsDateFilter,
      setSelectedOwnerUserId: session.setSelectedOwnerUserId, setTab: state.setTab, statementAuditRuns: session.statementAuditRuns, statementUploads: session.statementUploads, syncProvider: session.syncProvider,
      syncingConnectionId: state.syncingConnectionId, tab: state.tab, todayDate: data.todayDate, toggleNotificationRule: session.toggleNotificationRule, transactions: session.transactions, updateAccount: session.updateAccount,
      updateBankConnection: session.updateBankConnection, updateBankingOrganization: session.updateBankingOrganization, updateNotificationRule: session.updateNotificationRule, updateStatementUploadMetadata: session.updateStatementUploadMetadata,
      updateTransaction: session.updateTransaction, uploadStatement: session.uploadStatement, viewer, viewingTransactionId: state.viewingTransactionId, closeEntityEndexGuideModal: data.closeEntityEndexGuideModal, contactForm: state.contactForm,
    },
    derived: data.pageDerivedState,
    entityDerived: data.entityDerivedData,
    helpers: data.pageUiHelpers,
    messageBoard: data.messageBoardActions,
    scope: data.scopeData,
    tables: {
      balanceLedgerTable: data.entityTables.balanceLedgerTable,
      debtorsTable: data.secondaryTables.debtorsTable,
      entitiesTable: data.entityTables.entitiesTable,
      payBillsTable: data.secondaryTables.payBillsTable,
      recurringTable: data.secondaryTables.recurringTable,
    },
    ui: {
      accountManagerOpen: state.accountManagerOpen, balanceLedgerTableRef: state.balanceLedgerTableRef, balancingBooks: state.balancingBooks, bankingOrganizationManagerOpen: state.bankingOrganizationManagerOpen,
      contactModalOpen: state.contactModalOpen, debtorsTableRef: state.debtorsTableRef, debtorModalOpen: state.debtorModalOpen, editingEntityEndexGuideId: state.editingEntityEndexGuideId, entitiesTableRef: state.entitiesTableRef,
      entityEndexFindingAll: state.entityEndexFindingAll, entityEndexGuideModalOpen: state.entityEndexGuideModalOpen, entityEndexLogOpen: state.entityEndexLogOpen, entityEndexQuery: state.entityEndexQuery,
      entityModalOpen: state.entityModalOpen, flashingSaveButtonKey: state.flashingSaveButtonKey, isHeaderLogoSpinning: state.isHeaderLogoSpinning, launchableBankingOrganizations: state.launchableBankingOrganizations,
      ledgerEntityModalSaving: state.ledgerEntityModalSaving, ledgerEntityModalTransactionId: state.ledgerEntityModalTransactionId, ledgerFilterPreset: state.ledgerFilterPreset, ledgerTableRef: state.ledgerTableRef,
      listSearchQueryByTab: state.listSearchQueryByTab, messageBoardLoading: state.messageBoardLoading, messageBoardMessages: state.messageBoardMessages, messageBoardOpen: state.messageBoardOpen,
      messageBoardUnacknowledgedCount: state.messageBoardUnacknowledgedCount, openBankingOrganizationPopup: state.openBankingOrganizationPopup, payBillsTableRef: state.payBillsTableRef, recurringModalOpen: state.recurringModalOpen,
      recurringTableRef: state.recurringTableRef, runningAIcountantHousekeeping: state.runningAIcountantHousekeeping, runningAIcountantWatchlist: state.runningAIcountantWatchlist, selectedBankAccountId: state.selectedBankAccountId,
      selectedBankingOrganizationId: state.selectedBankingOrganizationId, selectedDebtorId: state.selectedDebtorId, setAccountManagerOpen: state.setAccountManagerOpen, setBankingOrganizationManagerOpen: state.setBankingOrganizationManagerOpen,
      setEntityEndexLogOpen: state.setEntityEndexLogOpen, setEntityEndexQuery: state.setEntityEndexQuery, setEntityHistoryEntityId: state.setEntityHistoryEntityId, setLedgerFilterPreset: state.setLedgerFilterPreset,
      setListSearchQueryByTab: state.setListSearchQueryByTab, setMessageBoardOpen: state.setMessageBoardOpen, setSelectedBankAccountId: state.setSelectedBankAccountId, setSelectedBankingOrganizationId: state.setSelectedBankingOrganizationId,
      setSelectedDebtorId: state.setSelectedDebtorId, setSettingsMenuOpen: state.setSettingsMenuOpen, settingsButtonRef: state.settingsButtonRef, settingsMenuOpen: state.settingsMenuOpen,
      settingsMenuPosition: state.settingsMenuPosition, settingsMenuRef: state.settingsMenuRef, summaryWindow: state.summaryWindow, syncHelpError: state.syncHelpError, syncHelpOpen: state.syncHelpOpen, syncHelpToken: state.syncHelpToken,
      transactionModalMode: state.transactionModalMode, transactionModalOpen: state.transactionModalOpen, transactionModalVariant: state.transactionModalVariant,
    },
  });
}
